title: Workshops by Will
email: will@will-russell.com
description: >- # this means to ignore newlines until "baseurl:"
  All resources for my workshops can be found here!
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://workshops.will-russell.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: wrussell1999
github_username:  wrussell1999

# Build settings
theme: just-the-docs
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
